const { pool } = require('../config/database');

const query = (text, params) => pool.query(text, params);

class TaskFixed {
  static async create({ 
    controlId, 
    title, 
    description, 
    status = 'pending', 
    priority = 'medium', 
    category, 
    assigneeId, 
    dueDate, 
    estimatedHours, 
    taskType = 'remediation', 
    autoGenerated = false 
  }) {
    // Tasks are now org-independent, so no organizationId needed
    const result = await query(
      `INSERT INTO tasks (control_id, title, description, status, priority, category, assignee_id, due_date, estimated_hours, auto_generated, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
       RETURNING *`,
      [controlId, title, description, status, priority, category, assigneeId, dueDate, estimatedHours, autoGenerated]
    );
    return result.rows[0];
  }

  static async findById(id) {
    const result = await query(
      `SELECT t.*, 
              c.title as control_title, c.description as control_description,
              u1.first_name as assignee_first_name, u1.last_name as assignee_last_name
       FROM tasks t
       JOIN controls c ON t.control_id = c.id
       LEFT JOIN users u1 ON t.assignee_id = u1.id
       WHERE t.id = $1`,
      [id]
    );
    return result.rows[0];
  }

  static async findByControlId(controlId, organizationId) {
    // FIXED: Now uses task_assignments instead of organization_id
    const result = await query(
      `SELECT DISTINCT t.*, 
              u1.first_name as assignee_first_name, u1.last_name as assignee_last_name,
              ta.status as assignment_status,
              ta.priority as assignment_priority,
              ta.due_date as assignment_due_date,
              ta.entity_id,
              e.name as entity_name
       FROM tasks t
       JOIN task_assignments ta ON t.id = ta.task_id
       JOIN entities e ON ta.entity_id = e.id
       LEFT JOIN users u1 ON ta.assigned_to = u1.id
       WHERE t.control_id = $1 AND e.organization_id = $2
       ORDER BY t.created_at DESC`,
      [controlId, organizationId]
    );
    return result.rows;
  }

  static async findByUserId(userId, organizationId) {
    // FIXED: Now uses task_assignments instead of organization_id
    const result = await query(
      `SELECT DISTINCT t.*, 
              c.title as control_title, c.description as control_description,
              ta.status as assignment_status,
              ta.priority as assignment_priority,
              ta.due_date as assignment_due_date,
              ta.entity_id,
              e.name as entity_name
       FROM tasks t
       JOIN task_assignments ta ON t.id = ta.task_id
       JOIN entities e ON ta.entity_id = e.id
       JOIN controls c ON t.control_id = c.id
       WHERE ta.assigned_to = $1 AND e.organization_id = $2
       ORDER BY ta.assignment_due_date ASC, ta.priority DESC`,
      [userId, organizationId]
    );
    return result.rows;
  }

  static async findByEntityId(entityId, organizationId) {
    // FIXED: Now uses task_assignments instead of complex joins
    const result = await query(
      `SELECT t.*, 
              c.title as control_title, c.description as control_description,
              u1.first_name as assignee_first_name, u1.last_name as assignee_last_name,
              ta.status as assignment_status,
              ta.priority as assignment_priority,
              ta.due_date as assignment_due_date
       FROM tasks t
       JOIN task_assignments ta ON t.id = ta.task_id
       JOIN controls c ON t.control_id = c.id
       LEFT JOIN users u1 ON ta.assigned_to = u1.id
       WHERE ta.entity_id = $1
       ORDER BY ta.assignment_due_date ASC, ta.priority DESC`,
      [entityId]
    );
    return result.rows;
  }

  static async assignToEntity(taskId, entityId, assignedTo = null, priority = 'medium', dueDate = null) {
    // NEW: Assign a task to an entity
    const result = await query(
      `INSERT INTO task_assignments (task_id, entity_id, assigned_to, priority, due_date, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
       ON CONFLICT (task_id, entity_id) 
       DO UPDATE SET 
         assigned_to = EXCLUDED.assigned_to,
         priority = EXCLUDED.priority,
         due_date = EXCLUDED.due_date,
         updated_at = NOW()
       RETURNING *`,
      [taskId, entityId, assignedTo, priority, dueDate]
    );
    return result.rows[0];
  }

  static async unassignFromEntity(taskId, entityId) {
    // NEW: Remove task assignment from entity
    const result = await query(
      `DELETE FROM task_assignments 
       WHERE task_id = $1 AND entity_id = $2
       RETURNING *`,
      [taskId, entityId]
    );
    return result.rows[0];
  }

  static async updateAssignmentStatus(taskId, entityId, status, progress = null, actualHours = null) {
    // NEW: Update assignment status (not the task itself)
    const updates = [];
    const values = [];
    let paramCount = 1;

    if (status !== undefined) { 
      updates.push(`status = $${paramCount++}`); 
      values.push(status);
      
      // Set completed_at when status is completed
      if (status === 'completed') {
        updates.push(`completed_at = CURRENT_TIMESTAMP`);
      } else if (status !== 'completed') {
        updates.push(`completed_at = NULL`);
      }
    }
    if (progress !== undefined) { 
      updates.push(`progress = $${paramCount++}`); 
      values.push(progress); 
    }
    if (actualHours !== undefined) { 
      updates.push(`actual_hours = $${paramCount++}`); 
      values.push(actualHours); 
    }

    if (updates.length === 0) {
      return await TaskFixed.findAssignmentById(taskId, entityId);
    }

    updates.push(`updated_at = CURRENT_TIMESTAMP`);
    values.push(taskId, entityId);

    const result = await query(
      `UPDATE task_assignments 
       SET ${updates.join(', ')} 
       WHERE task_id = $${paramCount++} AND entity_id = $${paramCount++} 
       RETURNING *`,
      values
    );
    return result.rows[0];
  }

  static async findAssignmentById(taskId, entityId) {
    const result = await query(
      `SELECT * FROM task_assignments 
       WHERE task_id = $1 AND entity_id = $2`,
      [taskId, entityId]
    );
    return result.rows[0];
  }

  // Keep other methods that don't depend on organization_id
  static async findAll(filters = {}) {
    let queryText = `
      SELECT DISTINCT t.*, 
             c.title as control_title, c.description as control_description,
             f.id as framework_id, f.name as framework_name, f.region as framework_region,
             u1.first_name as assignee_first_name, u1.last_name as assignee_last_name
      FROM tasks t
      JOIN controls c ON t.control_id = c.id
      JOIN frameworks f ON c.framework_id = f.id
      LEFT JOIN users u1 ON t.assignee_id = u1.id
      WHERE 1=1
    `;
    const params = [];
    let paramCount = 1;

    if (filters.status) {
      queryText += ` AND t.status = $${paramCount++}`;
      params.push(filters.status);
    }
    if (filters.priority) {
      queryText += ` AND t.priority = $${paramCount++}`;
      params.push(filters.priority);
    }
    if (filters.assigneeId) {
      queryText += ` AND t.assignee_id = $${paramCount++}`;
      params.push(filters.assigneeId);
    }
    if (filters.controlId) {
      queryText += ` AND t.control_id = $${paramCount++}`;
      params.push(filters.controlId);
    }
    if (filters.category) {
      queryText += ` AND t.category = $${paramCount++}`;
      params.push(filters.category);
    }

    // Add sorting
    const sortBy = filters.sortBy || 'created_at';
    const sortOrder = filters.sortOrder || 'DESC';
    queryText += ` ORDER BY t.${sortBy} ${sortOrder}`;

    // Add pagination
    if (filters.limit) {
      queryText += ` LIMIT $${paramCount++}`;
      params.push(parseInt(filters.limit));
    }
    if (filters.offset) {
      queryText += ` OFFSET $${paramCount++}`;
      params.push(parseInt(filters.offset));
    }

    const result = await query(queryText, params);
    return result.rows;
  }

  static async update(id, { title, description, priority, category, assigneeId, dueDate, estimatedHours, actualHours, progress, evidenceAttached, blockers }) {
    const updates = [];
    const values = [];
    let paramCount = 1;

    if (title !== undefined) { updates.push(`title = $${paramCount++}`); values.push(title); }
    if (description !== undefined) { updates.push(`description = $${paramCount++}`); values.push(description); }
    if (priority !== undefined) { updates.push(`priority = $${paramCount++}`); values.push(priority); }
    if (category !== undefined) { updates.push(`category = $${paramCount++}`); values.push(category); }
    if (assigneeId !== undefined) { updates.push(`assignee_id = $${paramCount++}`); values.push(assigneeId); }
    if (dueDate !== undefined) { updates.push(`due_date = $${paramCount++}`); values.push(dueDate); }
    if (estimatedHours !== undefined) { updates.push(`estimated_hours = $${paramCount++}`); values.push(estimatedHours); }
    if (actualHours !== undefined) { updates.push(`actual_hours = $${paramCount++}`); values.push(actualHours); }
    if (progress !== undefined) { updates.push(`progress = $${paramCount++}`); values.push(progress); }
    if (evidenceAttached !== undefined) { updates.push(`evidence_attached = $${paramCount++}`); values.push(evidenceAttached); }
    if (blockers !== undefined) { updates.push(`blockers = $${paramCount++}`); values.push(blockers); }

    if (updates.length === 0) {
      return await TaskFixed.findById(id);
    }

    updates.push(`updated_at = CURRENT_TIMESTAMP`);
    values.push(id);

    const result = await query(
      `UPDATE tasks SET ${updates.join(', ')} WHERE id = $${paramCount} RETURNING *`,
      values
    );
    return result.rows[0];
  }

  static async delete(id) {
    const result = await query(
      `DELETE FROM tasks WHERE id = $1 RETURNING id`,
      [id]
    );
    return result.rows[0];
  }
}

module.exports = TaskFixed;
