-- Add auto_generated column to tasks table
-- This migration adds the missing auto_generated column that the compliance engine expects

-- Add the auto_generated column to tasks table
ALTER TABLE tasks 
ADD COLUMN auto_generated BOOLEAN DEFAULT false NOT NULL;

-- Add an index for performance when filtering by auto_generated
CREATE INDEX idx_tasks_auto_generated ON tasks(auto_generated);

-- Add a comment for documentation
COMMENT ON COLUMN tasks.auto_generated IS 'Indicates if the task was automatically generated by the compliance engine';

-- Update existing tasks to be marked as manually created (auto_generated = false)
-- This is already the default, but being explicit
UPDATE tasks SET auto_generated = false WHERE auto_generated IS NULL;
